; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Mon Aug 08 2022 14:25:05 GMT+0200 (Central European Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


