; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Mon Aug 08 2022 14:25:06 GMT+0200 (Central European Summer Time)
G91               ; relative positioning
G1 H1 X+305 F5400 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F6000       ; go back a few mm
G1 H1 X+305 F360  ; move slowly to X axis endstop once more (second pass)
G90               ; absolute positioning

