; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Mon Aug 08 2022 14:25:06 GMT+0200 (Central European Summer Time)
G91              ; relative positioning
G1 H1 Z-255 F5400; move Z up until the endstop is triggered
G92 Z0		     ; set Z position to axis maximum (you may want to adjust this)

G1 Z10 F12000; lift Z relative to current position

