; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Mon Aug 08 2022 14:25:06 GMT+0200 (Central European Summer Time)

